// Export piano sample paths
export const pianoSamples = {
  A0: require('./piano-samples/A0.mp3'),
  C1: require('./piano-samples/C1.mp3'),
  'D#1': require('./piano-samples/Ds1.mp3'),
  'F#1': require('./piano-samples/Fs1.mp3'),
  A1: require('./piano-samples/A1.mp3'),
  C2: require('./piano-samples/C2.mp3'),
  'D#2': require('./piano-samples/Ds2.mp3'),
  'F#2': require('./piano-samples/Fs2.mp3'),
  A2: require('./piano-samples/A2.mp3'),
  C3: require('./piano-samples/C3.mp3'),
  'D#3': require('./piano-samples/Ds3.mp3'),
  'F#3': require('./piano-samples/Fs3.mp3'),
  A3: require('./piano-samples/A3.mp3'),
  C4: require('./piano-samples/C4.mp3'),
  'D#4': require('./piano-samples/Ds4.mp3'),
  'F#4': require('./piano-samples/Fs4.mp3'),
  A4: require('./piano-samples/A4.mp3'),
  C5: require('./piano-samples/C5.mp3'),
  'D#5': require('./piano-samples/Ds5.mp3'),
  'F#5': require('./piano-samples/Fs5.mp3'),
  A5: require('./piano-samples/A5.mp3'),
  C6: require('./piano-samples/C6.mp3'),
  'D#6': require('./piano-samples/Ds6.mp3'),
  'F#6': require('./piano-samples/Fs6.mp3'),
  A6: require('./piano-samples/A6.mp3'),
  C7: require('./piano-samples/C7.mp3'),
  'D#7': require('./piano-samples/Ds7.mp3'),
  'F#7': require('./piano-samples/Fs7.mp3'),
  A7: require('./piano-samples/A7.mp3'),
};